FROM python:3.12-alpine
WORKDIR /

# HOSTS
ENV MAINAPI_HOST=127.0.0.1:8080
ENV MODERATION_HOST=127.0.0.1:8001
ENV GRAFANA_API_HOST=127.0.0.1:8002
ENV LLM_API_HOST=127.0.0.1:8003

# ENV FOR MAINAPI
ENV POSTGRES_USERNAME=postgres
ENV POSTGRES_PASSWORD=123
ENV POSTGRES_HOST=postgres
ENV POSTGRES_PORT=5433
ENV POSTGRES_DATABASE=prod_mainapi
ENV REDIS_HOST=redis
ENV REDIS_PORT=6380
ENV IMAGES_MAXSIZE=5000000
ENV IMAGES_FILETYPES=png,jpg,jpeg,tiff,gif,webp,bmp

# ENV FOR LLM API
ENV YAGPT_CATALOG=<YAGPT_CATALOG>
ENV YAGPT_KEY=<YAGPT_KEY>

# ENV FOR GRAFANA API

# ENV FOR MODERATION API
ENV MOD_POSTGRES_USERNAME=postgres
ENV MOD_POSTGRES_PASSWORD=123
ENV MOD_POSTGRES_HOST=postgres
ENV MOD_POSTGRES_PORT=5433
ENV MOD_POSTGRES_DATABASE=prod_moderationapi

# ENV FOR TG BOT
ENV TGBOT_REDIS_HOST=redis
ENV TGBOT_REDIS_PORT=6380
ENV TGBOT_REDIS_DB=1
ENV TGBOT_TOKEN=<BOTTOKEN>

# INSTALL PYTHON LIBRARIES
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# EXPOSE PORTS
EXPOSE 8080
EXPOSE 8001
EXPOSE 8002
EXPOSE 8003

# COPY SOLUTION FOLDERS
COPY grafanaapi grafanaapi
COPY llmapi llmapi
COPY mainapi mainapi
COPY moderationapi moderationapi
COPY tgbot tgbot

# COPY RUN SCRIPT
COPY run.sh run.sh
RUN chmod +x run.sh

# RUN ALL APPS
CMD [ "/bin/sh", "run.sh" ]