import os

MOD_POSTGRES_USERNAME = os.getenv("MOD_POSTGRES_USERNAME", "postgres")
MOD_POSTGRES_PASSWORD = os.getenv("MOD_POSTGRES_PASSWORD", "123")
MOD_POSTGRES_HOST = os.getenv("MOD_POSTGRES_HOST", "localhost")
MOD_POSTGRES_PORT = os.getenv("MOD_POSTGRES_PORT", 5433)
MOD_POSTGRES_DATABASE = os.getenv("MOD_POSTGRES_DATABASE", "prod_moderationapi")

MAINAPI_HOST = os.getenv("MAINAPI_HOST", "127.0.0.1:8080")
MODERATION_HOST = os.getenv("MODERATION_HOST", "127.0.0.1:8001")
GRAFANA_API_HOST = os.getenv("GRAFANA_API_HOST", "127.0.0.1:8002")
LLM_API_HOST = os.getenv("LLM_API_HOST", "127.0.0.1:8003")